config/routes.rb
Rails.application.routes.draw do

  resources :customers
  resources :products do
    collection { post :import }
  end
  
  resources :orders

  root :to => 'products#index'

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  validates_presence_of :name, :phone
  validates_numericality_of :company_tax_id, :only_integer => true

  has_many :orders


end

app/models/order.rb
class Order < ActiveRecord::Base

  belongs_to :customer

  has_many :order_product_ships
  has_many :products, :through => :order_product_ships

  def order_number
  end

  def total_product_number
    self.order_product_ships.size
  end

  def product_list
    self.products.map{|p| p.name}
  end

  def product_info
    ships = OrderProductShip.where(:order_id => self.id)
    @order_information = ships.pluck(:product_id,:number,:subtotal)
    
    @info = Hash.new
    @order_information.each do |i|
      @info["#{i[0]}"]={:number => i[1], :subtotal => i[2]}
    end
  end

  def product_detail(p)
    @info["#{p}"]
  end

  def total_price
    ships = OrderProductShip.where(:order_id => self.id)
    ships.to_a.sum(&:subtotal) 
  end
end

app/models/order_product_ship.rb
class OrderProductShip < ActiveRecord::Base

  belongs_to :order
  belongs_to :product

end

app/models/product.rb
class Product < ActiveRecord::Base
  validates_presence_of :name, :unit, :price
  validates_uniqueness_of :name, :message => "你的名稱重複了"
  validates_numericality_of :price, :only_integer => true

  has_many :order_product_ships
  has_many :orders, :through => :order_product_ships

  require 'roo'

  def self.import(file)
    spreadsheet = open_spreadsheet(file)
    header = spreadsheet.row(1)
    Product.all.delete_all
    (2..spreadsheet.last_row).each do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
      row.to_hash[:id] = i
      product = new
      product.attributes = row.to_hash
      product.save!
    end
  end

  def self.open_spreadsheet(file)
    case File.extname(file.original_filename)
    when ".csv" then Roo::Csv.new(file.path, :ignore)
    when ".xls" then Roo::Excel.new(file.path, :ignore)
    when ".xlsx" then Roo::Excelx.new(file.path, packed: nil, file_warning: :ignore)
    else raise "Unknown file type: #{file.original_filename}"
    end
  end
end

  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

  before_action :find_customer, :only =>[:show, :destroy]

  def index
    @customers = Customer.all
  end

  def new
    @customer = Customer.new
  end

  def show
  end

  def create
    @customer = Customer.new(customer_params)
    @customer.save
    redirect_to customers_path
  end

  def destroy
    @customer.delete
    redirect_to customers_path
  end


  private

  def find_customer
    @customer = Customer.find(params[:id])
  end

  def customer_params
    params.require(:customer).permit(:company, :company_tax_id, :name, :phone, :address)
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  
  before_action :find_order, :only => [:show, :update, :destroy]
  
  def index
    @orders = Order.all
  end 

  def new
    @order = Order.new
  end

  def create
    @order = Order.new(order_params)
    @order.save

    redirect_to order_path(@order)
  end

  def show
  end

  def update
    Order.find(params[:id]).update(order_params)

    if params[:order][:product_list] && params[:order][:order_number] !=""
      product_list = params[:order][:product_list]
      product_list.shift(1)

      number =params[:order][:order_number].to_i

      product_list.each do|p|
        product_id = p.to_i

        if product_id == 0
          break
        end  

        if OrderProductShip.where(:order_id => @order.id).find_by_product_id(product_id)

        else
          OrderProductShip.create( :order_id => params[:id], :product_id => product_id)
        end
        ships = OrderProductShip.where(:order_id => @order.id).find_by_product_id(product_id)
        ships.number = number

        product_price = Product.find(product_id).price

        ships.subtotal = product_price * number
        ships.save!
      end
    end

    @order.total = OrderProductShip.where(:order_id => @order.id).to_a.sum(&:subtotal)
    @order.save!

    redirect_to order_path(@order)
  end

  def destroy
    if params[:product_id]
      OrderProductShip.where(:order_id => @order.id).find_by_product_id(params[:product_id]).delete
      redirect_to order_path(@order)
    else
      @order.delete
      redirect_to orders_path
    end
  end

  private

  def find_order
    @order = Order.find(params[:id])
  end

  def order_params
    params.require(:order).permit(:name, :product_list, :phone, :address)
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :find_product, :only => [:show, :update, :destroy]
  
  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:notice] = "產品新增成功"
      redirect_to products_path
    else
      flash[:alert] = "產品新增失敗，檢查一下名稱是否重複，價格必須為阿拉伯數字，單位正確嗎？"
      render "new"
    end

  end

  def show
  end

  def update
    if @product.update(product_params)
      flash[:notice] = "產品成功更新"
      redirect_to products_path
    else
      flash[:alert] = "產品成功失敗，檢查一下名稱是否重複，價格必須為阿拉伯數字，單位正確嗎？"
      render "edit"
    end
  end

  def destroy
    @product.delete
    redirect_to products_path
  end

  def import
    Product.import(params[:file])
    redirect_to root_url, notice: "Products imported."
  end

  private

  def product_params
    params.require(:product).permit(:name, :unit, :price, :description)
  end

  def find_product
    @product = Product.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/customers/_form.html.erb
<div class="form-group">
  <%= f.label :company, "公司" %>
  <%= f.text_field :company %>
</div>

<div class="form-group">
  <%= f.label :company_tax_id, "統一編號" %>
  <%= f.text_field :company_tax_id %>
</div>

<div class="form-group">
  <%= f.label :name, "姓名" %>
  <%= f.text_field :name %>
</div>

<div class="form-group">
  <%= f.label :phone, "電話" %>
  <%= f.text_field :phone %>
</div>

<div class="form-group">
  <%= f.label :address, "地址" %>
  <%= f.text_field :address %>
</div>

app/views/customers/index.html.erb
<h1>客戶資訊</h1>

<h1><%= link_to "建立新客戶", new_customer_path, :class =>"btn btn-warning btn-lg"%></h1>

<table class="table">
  <tr>
    <td>ID</td>
    <td>公司</td>
    <td>統一編號</td>
    <td>姓名</td>
    <td>電話</td>
    <td>住址</td>
  </tr>

  <%@customers.each do |c|%>
    <tr>
      <td><%=link_to c.id, customer_path(c)%></td>
      <td><%=c.company%></td>
      <td><%=c.company_tax_id%></td>
      <td><%=c.name%></td>
      <td><%=c.phone%></td>
      <td><%=c.address%></td>
      <td><%= link_to "刪除", customer_path(c), :method => :delete, :class =>"btn btn-danger", data: {confirm: "你確定要刪除客戶： #{c.company}的#{c.name}?"}%></td>
    </tr>
  <%end%>
</table>

app/views/customers/new.html.erb
<h1>建立新客戶</h1>

<%= form_for @customer, :url => customers_path, :method => :post do |f|%>
  <%= render :partial => 'form', :locals => { :f => f} %>
  
  <%= f.submit "建立新客戶" %>
<%end%>

app/views/customers/show.html.erb
<h1>客戶資訊</h1>

<%=form_for @customer, :url => customer_path(@customer), :method => :patch do|f|%>

  <%= render :partial => 'form', :locals => { :f => f} %>

  <%= f.submit "送出更改" %>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShoppingCart</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>




<div class="container">
    <div class="col-md-12">
      <div class="row">
        <div class="col-md-4 col-sm-4">
          <div id="order-btn">
            <%= link_to orders_path do%>
              <div>
                <h1>訂單</h1>
              </div>
            <%end%>
          </div>
        </div>

        <div class="col-md-4 col-sm-4">
          <div id="product-btn">
            <%= link_to products_path do%>
              <div>
                <h1>產品</h1>
              </div>
            <%end%>
          </div>
        </div>

        <div class="col-md-4 col-sm-4">
          <div id="customer-btn">
            <%= link_to customers_path do%>
              <div>
                <h1>客戶</h1>
              </div>
            <%end%>
          </div>
        </div> 
      </div> 
    </div>

    <div class="col-md-12">
        <% if flash[:alert].present? %>
          <div class="alert alert-danger" role="alert">
            <%= flash[:alert]%>
          </div>
        <%end%>
        <% if flash[:notice].present? %>
          <div class="alert alert-success" role="alert">
            <%= flash[:notice]%>
          </div>
        <%end%>

        <%= yield %>
    </div>
</div>


</body>
</html>

app/views/orders/index.html.erb
<h1>訂單資訊</h1>

<h1><%= link_to "建立新訂單", new_order_path, :class => "btn btn-warning btn-lg"%></h1>

<table class="table">
  <tr>
    <td>編號</td>
    <td>姓名</td>
    <td>電話</td>
    <td>總價</td>  
  </tr>
  <%@orders.each do |order|%>
    <tr>
      <td><%=link_to order.id, order_path(order)%></td>
      <td><%=order.name%></td>
      <td><%=order.phone%></td>
      <td><%=order.total_price%>元</td>
      <td><%=link_to "刪除", order_path(order), :method => :delete, :class =>"btn btn-danger", data: {confirm: "你確定要刪除： #{order.name}的訂單?"}%></td>
    </tr>
  <%end%>
</table>

app/views/orders/new.html.erb
<h1>新訂單資訊</h1>

<h4>訂單編號:<%=@order.id%></h4>
<%= form_for @order, :url => orders_path, :method => :post  do |f|%>
  
  <div class="form-group">
    <%= f.label :name, "姓名" %>
    <%= f.text_field :name %>
  </div>
  
  <div class="form-group">
    <%= f.label :address, "地址" %>
    <%= f.text_field :address %>
  </div>
  
  <div class="form-group">
    <%= f.label :phone, "電話" %>
    <%= f.text_field :phone %>
  </div>

  <%= f.submit "送出", :class => "btn btn-info btn-lg" %>
<%end%>

app/views/orders/show.html.erb
<h1>訂單資訊</h1>

<h4>訂單編號:<%=@order.id%></h4>
<%= form_for @order, :url => order_path(@order), :method => :patch do |f|%>

  <div class="form-group">
    <%= f.label :name, "姓名" %>
    <%= f.text_field :name %>
  </div>
  <div class="form-group">
    <%= f.label :address, "地址" %>
    <%= f.text_field :address %>
  </div>
  <div class="form-group">
    <%= f.label :phone, "電話" %>
    <%= f.text_field :phone %>
  </div>

  <div class="form-group">
    <%= f.label :product_list, "產品" %>
    <%= f.select :product_list, Product.all.map{ |x| [x.name, x.id]}, {}, :multiple => "false" , :class => "form-control"%>
  </div>

  <div class="form-group">
    <%= f.label :order_number, "數量" %>
    <%= f.text_field :order_number, :class => "form-control"%>
  </div>

  <%= f.submit "送出更新",:class => "btn btn-info btn-lg" %>
<%end%>

<br>
<table class="table">
  <tr>
    <td>產品ID</td>
    <td>品名</td>
    <td>單價</td>
    <td>數量</td>
    <td>單位</td>
    <td>小記</td>
  </tr>

  <% @order.product_info %>
  <% @order.products.each do |p|%>
    <tr>
      <td><%=p.id%></td> 
      <td><%=p.name%></td>
      <td><%=p.price%></td>
      <td><%=@order.product_detail(p.id)[:number]%></td>
      <td><%=p.unit%></td>
      <td><%=@order.product_detail(p.id)[:subtotal]%>元</td>
      <td><%=link_to "刪除", order_path(@order,:product_id => p.id), :method=>:delete, :class => "btn btn-danger"%></td>
    </tr>
  <%end%>
</table>


<div class="col-md-4 col-md-offset-6">
  <h4> 總計：<%=@order.total_price%> 元 
  <%=link_to "完成訂單", orders_path, :class => "btn btn-success btn-lg" %></h4>
</div>

<script>
  $("#order_product_list").select2({
     tags: <%=raw Product.all.map{ |p| p.name }.to_json %>,
     tokenSeparators: [',', ' ']
   });
</script>

app/views/products/_form.html.erb
<div class="form-group">
  <%= f.label :name, "品名" %>
  <%= f.text_field :name %>
</div>

<div class="form-group">
  <%= f.label :description, "敘述" %>
  <%= f.text_area :description %>
</div>

<div class="form-group">
  <%= f.label :unit, "單位" %>
  <%= f.text_field :unit %>
</div>

<div class="form-group">
  <%= f.label :price, "單價" %>
  <%= f.text_field :price %>
</div>

app/views/products/index.html.erb
<h1>產品清單</h1>

<h1><%= link_to "新建產品", new_product_path, :class =>"btn btn-warning btn-lg"%></h1>

<table class="table">
  <tr>
    <td>品名</td>
    <td>敘述</td>
    <td>單位</td>
    <td>價格(台幣)</td>
  </tr>

  <% @products.each do |p|%>
    <tr> 
      <td><%=link_to p.name, product_path(p)%></td>
      <td><%=p.description%></td>
      <td><%=p.unit%></td>
      <td><%=p.price%></td>
      <td><%= link_to "刪除", product_path(p),:method => :delete, :class => "btn btn-danger", data: {confirm: "你確定要刪除： #{p.name}:#{p.try(:description)}?"}%></td>
    </tr>
  <%end%>
</table>

<h2>Import Products</h2>

<%= form_tag import_products_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import" %>
<% end %>

app/views/products/new.html.erb
<h1>建立產品</h1>

<%=form_for @product, :url => products_path, :method => :post do|f|%>
  <%= render :partial => 'form', :locals => { :f => f} %>

  <%= f.submit "建立產品" %>

<%end%>

app/views/products/show.html.erb
<h1>product show</h1>

<%=form_for @product, :url => product_path(@product), :method => :patch do|f|%>
  <%= render :partial => 'form', :locals => { :f => f} %>

  <%= f.submit "送出更新" %>

<%end%>